version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4  

  portainer:
    image: portainer/portainer-ce

  wpfo.gateway:
    image: ${DOCKER_REGISTRY-}wpfogateway
    build:
      context: .
      dockerfile: WPFO.GateWay/Dockerfile

  wpfo.basket.api:
    image: ${DOCKER_REGISTRY-}wpfobasketapi
    build:
      context: .
      dockerfile: WPFO.Basket/Dockerfile


  wpfo.catalog.api:
    image: ${DOCKER_REGISTRY-}wpfocatalogapi
    build:
      context: .
      dockerfile: WPFO.Catalog.Api/Dockerfile


  wpfo.discount.api:
    image: ${DOCKER_REGISTRY-}wpfodiscountapi
    build:
      context: .
      dockerfile: WPFO.Discount.Api/Dockerfile


  wpfo.discountrpc:
    image: ${DOCKER_REGISTRY-}wpfodiscountrpc
    build:
      context: .
      dockerfile: WPFO.DiscountRPC/Dockerfile


  wpfo.ordering.api:
    image: ${DOCKER_REGISTRY-}wpfoorderingapi
    build:
      context: .
      dockerfile: WPFO.Ordering.API/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
  elasticsearch-data: